FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libreoffice-core libreoffice-writer \
    redis-server \
    gcc \
    g++ \
    build-essential \
    git \
    libmagic1 \
    ffmpeg \
    libsndfile1 \
    wget \
    ca-certificates \
    curl \
    util-linux \
    procps \
    && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \ 
    && apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

ENV ENVIRONMENT=development
ENV APP_ENV=development
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

RUN wget https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem -O /app/global-bundle.pem

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir setuptools wheel cython && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chmod +x ./start.sh

EXPOSE 8000

ENTRYPOINT ["sh", "/app/start.sh"]