import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Flex, Card, Input } from "antd";
import { SearchOutlined } from "@ant-design/icons";
import AdminSettingsPage from "../../components/AdminDashboard/AdminSettingsPage";
import UserDocuments from "../../components/AdminDashboard/UserDocuments";
import UserGeneratedContent from "../../components/AdminDashboard/UserGeneratedContent";

const AdminDashboardPage = () => {
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedUser, setSelectedUser] = useState(null);
  const navigate = useNavigate();
  const isMobile = window.innerWidth <= 768;

  return (
    <Flex vertical gap="large" style={{ height: "100%" }}>
      <Input
        placeholder="Search"
        value={searchTerm}
        onChange={(e) => setSearchTerm(e.target.value)}
        suffix={<SearchOutlined />}
        style={{ width: isMobile ? "100%" : "40%", borderRadius: "24px" }}
      />
      <Card>
        <AdminSettingsPage
          searchTerm={searchTerm}
          setSelectedUser={setSelectedUser}
        />
      </Card>
      {selectedUser && (
        <Flex
          vertical={isMobile}
          justify="center"
          style={{ width: "100%", height: "100%" }}
          gap="middle"
        >
          <Card
            style={{ width: isMobile ? "100%" : "50%", height: "100%" }}
            styles={{ body: { height: "calc(100% - 56px)", padding: 0 } }}
            title={`Documents Uploaded by: ${selectedUser.username}`}
          >
            <UserDocuments selectedUser={selectedUser} />
          </Card>
          <Card
            style={{ width: isMobile ? "100%" : "50%" }}
            styles={{ body: { height: "calc(100% - 56px)", padding: 0 } }}
            title={`Content Generated by: ${selectedUser.username}`}
          >
            <UserGeneratedContent
              selectedUser={selectedUser}
              redirectTo={navigate}
            />
          </Card>
        </Flex>
      )}
    </Flex>
  );
};

export default AdminDashboardPage;
